title: jaumecapdevila
email: contact@jaumecapdevila.net
description: >-
  Personal blog
baseurl: ''
url: ''
twitter_username: otherjaume
github_username: jaumecapdevila

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
